##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_screen
description: "TODO: Add a description"
version: 0.1.0
repository: https://github.com/robmllze/df_screen
publish_to: none

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter

  df_collection: ^0.4.0
  df_config: ^0.4.0
  df_generate_dart_models_core: ^0.3.2
  df_log: ^0.2.1
  df_pod: ^0.11.8
  df_scalable: ^0.2.7
  df_type: ^0.5.2
  df_cleanup: ^0.2.2
  df_debouncer: ^0.2.1

  after_layout: ^1.2.0
  device_info_plus: ^10.1.2
  go_router: ^14.2.6
  meta: ^1.15.0

  df_screen_core:
    git:
      url: https://github.com/robmllze/df_screen_core
      ref: main

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
